- hosts: web
  become: yes
  gather_facts: false

  pre_tasks:
    # AL2 needs Python2 + rpm bindings for the yum Ansible module
    - name: Bootstrap Python2 + rpm bindings
      raw: |
        set -e
        (command -v python2 >/dev/null 2>&1) || yum install -y python2
        python2 - <<'PY' >/dev/null 2>&1 || yum install -y rpm-python
        import rpm
        PY
      changed_when: false

    - name: Gather facts (now that Python exists)
      setup:

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Ensure ServerName is set (avoid FQDN fatal on some builds)
      copy:
        dest: /etc/httpd/conf.d/servername.conf
        mode: "0644"
        content: "ServerName localhost\n"

    # If you previously created an 8080-only vhost and want to keep ONLY port 80 for this test, remove it:
    - name: Remove any previous 8080 custom conf (optional)
      file:
        path: /etc/httpd/conf.d/listen-8080.conf
        state: absent

    - name: Ensure /var/www/html/jw exists (ALB health path)
      file:
        path: /var/www/html/jw
        state: directory
        mode: "0755"

    - name: Health-check page for /jw/
      copy:
        dest: /var/www/html/jw/index.html
        mode: "0644"
        content: "OK\n"

    - name: Simple index page
      copy:
        dest: /var/www/html/index.html
        mode: "0644"
        content: "<h1>Apache OK</h1>\n"

    - name: Validate Apache config
      shell: httpd -t
      register: httpdtest
      changed_when: false

    - name: Show validation output
      debug:
        var: httpdtest.stdout_lines

    - name: Start/enable Apache
      service:
        name: httpd
        state: started
        enabled: yes