- hosts: web
  become: yes
  gather_facts: false

  tasks:
    - name: Install CloudWatch Agent
      yum:
        name: amazon-cloudwatch-agent
        state: present

    - name: Create CloudWatch Agent config
      copy:
        dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
        mode: "0644"
        content: |
          {
            "agent": {
              "metrics_collection_interval": 60,
              "logfile": "/opt/aws/amazon-cloudwatch-agent/logs/agent.log"
            },
            "metrics": {
              "append_dimensions": {
                "AutoScalingGroupName": "${aws:AutoScalingGroupName}",
                "InstanceId": "${aws:InstanceId}"
              },
              "aggregation_dimensions": [["AutoScalingGroupName"]],
              "metrics_collected": {
                "cpu":   { "measurement": ["cpu_usage_idle","cpu_usage_user","cpu_usage_system"], "metrics_collection_interval": 60, "resources": ["*"] },
                "mem":   { "measurement": ["mem_used_percent","mem_available"], "metrics_collection_interval": 60 },
                "disk":  { "measurement": ["used_percent"], "resources": ["*"], "metrics_collection_interval": 60 },
                "netstat": { "measurement": ["tcp_established","tcp_time_wait"], "metrics_collection_interval": 60 },
                "procstat": [
                  { "pattern": "java",  "measurement": ["pid_count"], "metrics_collection_interval": 60, "dimensions": [{"Process":"java"}] },
                  { "pattern": "httpd", "measurement": ["pid_count"], "metrics_collection_interval": 60, "dimensions": [{"Process":"httpd"}] }
                ]
              }
            },
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    { "file_path": "/var/log/httpd/access_log", "log_group_name": "/${var.project_name}/apache/access", "log_stream_name": "{instance_id}", "timestamp_format": "%d/%b/%Y:%H:%M:%S %z" },
                    { "file_path": "/var/log/httpd/error_log",  "log_group_name": "/${var.project_name}/apache/error",  "log_stream_name": "{instance_id}" },
                    { "file_path": "/opt/joget/apache-tomcat/logs/catalina.out", "log_group_name": "/${var.project_name}/joget/catalina", "log_stream_name": "{instance_id}" }
                  ]
                }
              }
            }
          }

    - name: Enable & start CloudWatch Agent
      systemd:
        name: amazon-cloudwatch-agent
        enabled: yes
        state: restarted
